### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by socurrina** [aimeos/aimeos-flow#12]
Hi,

I am using Neos 3.0.6 version of Neos. While running this command ./flow aimeos:setup i get the following error 
_Required class "Aimeos\Flow\AimeosTypeConverter" could not be loaded properly for reflection._
Am i missing something ?

**Comment by aimeos** [comment]
That's a good question. Flow/Neos is very picky regarding any change which often results in such errors for various reasons. Did you try to clear the code cache? Sometimes, it only helps to delete the cache directory manually.

**Comment by socurrina** [comment]
Yes. I tried clearing the cache manually. But still it gives the same error :(

**Comment by socurrina** [comment]
Hi.. The error is gone after i tried to install it in a fresh neos setup. but when i tried to add the aimeos plugin on neos page I get following error
Template file "resource://Aimeos.Shop/Private/Templates/NodeTypes/Plugin.html" could not be loaded. Any idea how to resolve this?

**Comment by aimeos** [comment]
Aimeos is known to work well in Flow applications, but it's feature incomplete in Neos. We are still looking for Neos experts who can help us to get a fully working version for Neos.
