### ISSUE TITLE
<f:base /> was removed in flow 5.0.3

### ISSUE THREAD

**Issue by flosolcher** [aimeos/aimeos-flow#19]
The viewhelper f:base was removed in flow 5.0.3 so you should remove it from the Layout.html
http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/ChangeLogs/503.html

**Comment by aimeos** [comment]
Thanks for the hint! Are you able to create a pull request for this?

**Comment by aimeos** [comment]
Fixed in 2018.10 release
