### ISSUE TITLE
when running ./flow aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by beechit** [aimeos/aimeos-flow#2]
I get the following error:

PHP Fatal error:  Class 'MW_Setup_Task_MShopAddLocaleData' not found in /Packages/Libraries/arcavias/arcavias-core/lib/mshoplib/setup/MShopAddLocaleLangCurData.php on line 13

tested with flow 2.3.3

**Comment by aimeos** [comment]
We tried several times and several combinations but are not able to reproduce the error. Nevertheless, this doesn't mean it isn't there. Maybe it's something that is different in your environment. Could you please add

```
echo "\n".get_include_path()."\n";
```

in this line: https://github.com/aimeos/aimeos-flow/blob/master/Classes/Aimeos/Shop/Command/AimeosCommandController.php#L140

The most likely reason is that the include paths haven't been set correctly.

**Comment by beechit** [comment]
`$./flow aimeos:setup --option=setup/default/demo:1`

``` php
/var/www/flow/beechit-aimeos-flow-shop/Packages/Libraries/arcavias/arcavias-core/lib/mshoplib/setup:/var/www/flow/beechit-aimeos-flow-shop/Packages/Libraries/arcavias/arcavias-core/lib/mshoplib/setup/default:/var/www/flow/beechit-aimeos-flow-shop/Packages/Libraries/phpunit/php-text-template:/var/www/flow/beechit-aimeos-flow-shop/Packages/Libraries/phpunit/php-timer:/var/www/flow/beechit-aimeos-flow-shop/Packages/Libraries/phpunit/php-file-iterator:.:/usr/share/php:/usr/share/pear
```

**Comment by aimeos** [comment]
I've made a small change in the setup command method that might fix the issue. Can you please execute `composer update` and try again?

**Comment by beechit** [comment]
That did the trick, thank you,  ill continue testing, if it is what i need i will do the dutch translation.
