### ISSUE TITLE
Missing step in the documentation?

### ISSUE THREAD

**Issue by mrimann** [aimeos/aimeos-flow#7]
Hi

I've started a fresh Neos 2.0 installation and followed your steps to get Aimeos added. But I can't reach the store frontend (/shop/list) and the admin area (/shop/admin).

What I see is the following error:
`NOTICE    Flow                 No authentication entry point found for active tokens, therefore cannot authenticate or redirect to authentication automatically.`

And if I leave out adding the Subroutes to the global route definition, then it just ends up in a "page not found" error.

Is there something missing in the documentation that needs to be done, to get Aimeos up and running?

**Comment by aimeos** [comment]
The aimeos-flow package is not yet fully adapted to all Neos requirements. For example, your problem relates to the fact that Neos doesn't allow unrestricted access and requires an access policy definition.

**Comment by mrimann** [comment]
Tried it, works, here's a PR to extend the manual: https://github.com/mrimann/aimeos-flow/pull/1

**Comment by aimeos** [comment]
Cool! Can you open a PR in aimeos/aimeos-flow?

**Comment by mrimann** [comment]
Ooops, opened a PR in my own fork... Now here you go in the correct repo: https://github.com/aimeos/aimeos-flow/pull/8
